### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Aravind4525** [Soulter/hugging-chat-api#233]
ERROR:root:No `type` found in response: {'message': 'An error occurred', 'errorId': '872cc721-4df6-42ef-82c8-a56b35eafaa3'}
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\New_PiCourseSearch\bc_pi.py", line 154, in <module>
    result = pisearch_courses(searchinput=input_text, course_content_id=course_content_id, standard=level,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\New_PiCourseSearch\bc_ut.py", line 631, in inner
    f = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\New_PiCourseSearch\bc_pi.py", line 17, in pisearch_courses
    print("chat_response : ", chat_response)
  File "C:\Users\Admin\PycharmProjects\New_PiCourseSearch\venv\Lib\site-packages\hugchat\message.py", line 233, in __str__
    return self.wait_until_done()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\New_PiCourseSearch\venv\Lib\site-packages\hugchat\message.py", line 203, in wait_until_done
    self.__next__()
  File "C:\Users\Admin\PycharmProjects\New_PiCourseSearch\venv\Lib\site-packages\hugchat\message.py", line 158, in __next__
    raise self.error
  File "C:\Users\Admin\PycharmProjects\New_PiCourseSearch\venv\Lib\site-packages\hugchat\message.py", line 105, in __next__
    self._filterResponse(a)
  File "C:\Users\Admin\PycharmProjects\New_PiCourseSearch\venv\Lib\site-packages\hugchat\message.py", line 89, in _filterResponse
    raise ChatError(f"Server returns an error: {obj['message']}")
hugchat.exceptions.ChatError: Server returns an error: An error occurred
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\New_PiCourseSearch\venv\Lib\site-packages\hugchat\hugchat.py", line 734, in _stream_query
    yield obj
GeneratorExit
Exception ignored in: <generator object ChatBot._stream_query at 0x000001FC2915D1B0>
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\New_PiCourseSearch\venv\Lib\site-packages\hugchat\hugchat.py", line 744, in _stream_query
hugchat.exceptions.ChatError: Failed to parse response: {"message":"An error occurred","errorId":"872cc721-4df6-42ef-82c8-a56b35eafaa3"}

**Comment by YWaller** [comment]
I have also started getting this error. Glad to know it's not my code all of a sudden!

**Comment by haytam776** [comment]
+1 Me too, my code before 3 hours ago work fine, but now it's not work with this error

**Comment by Whitelisted1** [comment]
This seems to be because of the fact that [HuggingChat](https://huggingface.co/chat/) has transitioned over to sending model queries as a Form requests in order to send files, shown when we look at the request sent in HuggingChat:

```
------WebKitFormBoundaryXebZOGiPuxr6B21Z
Content-Disposition: form-data; name="data"

{"inputs":"Hi!","id":"c5a92bea-3722-4d8b-9a59-bfc2ea7bb0e4","is_retry":false,"is_continue":false,"web_search":false,"tools":{}}
------WebKitFormBoundaryXebZOGiPuxr6B21Z--
```

**Comment by qahsi2004** [comment]
@Whitelisted1 Can you please suggest a solution for this issue? I have a project due by tomorrow and I really want to get it sorted out asap. Thank you.

**Comment by YWaller** [comment]
@qahsi2004 I intend this to be a _very gentle rebuke,_ but:  "your failure to plan ahead is not my emergency" should be his response. None of us are paying the guy. I've spent some time looking through message.py trying to sort it out myself and failing badly (meaning, no one rely on @YWaller to fix this lol), but it takes time. This isn't exactly a corporate sponsored git repo, aye?

If you need it that badly, all the code is in python. Dive in. Fix it. Add "open source contributor" to your resume. It's either in hugchat.py or message.py I'm pretty sure.

**Comment by thomaspj10** [comment]
I've created a PR, which fixes this issue.

**Comment by Soulter** [comment]
Fixed this error in the latest version v0.4.8 and Thanks @thomaspj10 .

**Comment by Besugo03** [comment]
Sorry but i'm still getting this error... am i doing something wrong?

This is the code i am using:
```python
from hugchat import hugchat
from hugchat.login import Login

EMAIL = # My email
PASSWD = # My passwd

sign = Login(EMAIL, PASSWD)
cookie_path_dir = "./cookies/" # NOTE: trailing slash (/) is required to avoid errors
cookies = sign.login(cookie_dir_path=cookie_path_dir, save_cookies=True)

# Create your ChatBot
chatbot = hugchat.ChatBot(cookies=cookies.get_dict())  # or cookie_path="usercookies/<email>.json"

# Non stream response
query_result = chatbot.chat("Hi!")
print(query_result) # or query_result.text or query_result["text"]
```
Output : 
`> ERROR:root:No type found in response: {'message': 'An error occurred', 'errorId': 'd7a3030e-29c9-45a2-ad6f-4400733eaf4a'}`
```
Exception has occurred: ChatError
Server returns an error: An error occurred
  File "C:\Users\alexp\Desktop\projects\hugchat_test.py", line 16, in <module>
    print(query_result) # or query_result.text or query_result["text"]
hugchat.exceptions.ChatError: Server returns an error: An error occurred
```

Output of "pip show" to show my current library version : 
```
PS C:\Users\alexp\Desktop\projects> pip show hugchat     
Name: hugchat
Version: 0.4.8
Summary: A huggingchat python api.
Home-page: https://github.com/Soulter/hugging-chat-api
Author: Soulter
Author-email: 905617992@qq.com
License: GNU Affero General Public License v3.0
Location: c:\users\alexp\appdata\local\programs\python\python310\lib\site-packages
Requires: requests, requests-toolbelt
Required-by:
```

**Comment by thomaspj10** [comment]
Works fine for me. Maybe re-install the package and restart your IDE? Is the package version installed under the correct Python version?

**Comment by Besugo03** [comment]
Sorry, this was an error from my end. I didn't notice i had two python interpreters in VSCode and it ended up installing the new version only on another one. Works like a charm! thanks @thomaspj10 ❤️

**Comment by tkarrergit** [comment]
Hello, i have this Problem again! ERROR:root:No `type` found in response: {'message': 'An error occurred', 'errorId': 'e7d78ef5-83b1-4c78-9561-4334f60beda4'} 

My Code:
from hugchat import hugchat
from hugchat.login import Login

EMAIL = "myemail"
PASSWD = "mypasswort"

sign = Login(EMAIL, PASSWD)
cookie_path_dir = "./cookies/" # NOTE: trailing slash (/) is required to avoid errors
cookies = sign.login(cookie_dir_path=cookie_path_dir, save_cookies=True)

# Create your ChatBot
chatbot = hugchat.ChatBot(cookies=cookies.get_dict())  # or cookie_path="usercookies/<email>.json"

# Non stream response
query_result = chatbot.chat("Hi!")
print(query_result) # or query_result.text or query_result["text"]

What am I doing wrong? hugchat ver. 0.4.10

**Comment by 766670** [comment]
@tkarrergit
Did you get any solution I am also facing same issue. As first it was running well but now same problem arises

I am using hugchat version 0.4.10

**Comment by nekronk** [comment]
Same issue!

`2024-08-18 08:55:21,115 - root - INFO - hf-chat loaded
2024-08-18 08:55:21,115 - root - INFO - token loaded
2024-08-18 08:55:21,496 - root - ERROR - No `type` found in response: {'message': 'An error occurred', 'errorId': 'f3d1ade6-3eb5-4fe0-a38a-3dc0b243faa1'}
2024-08-18 08:55:21,496 - handlers - ERROR - Error occurred: Server returns an error: An error occurred`

`$ pip show hugchat`
```
Name: hugchat
Version: 0.4.10
Summary: A huggingchat python api.
Home-page: https://github.com/Soulter/hugging-chat-api
Author: Soulter
Author-email: 905617992@qq.com
License: GNU Affero General Public License v3.0
Location: /home/runner/vstprsr/.pythonlibs/lib/python3.10/site-packages
Requires: requests, requests-toolbelt
Required-by: 
```

**Comment by Soulter** [comment]
@766670 @tkarrergit Hey guys, you can update to 0.4.11 and check it again.

**Comment by nekronk** [comment]
> @tkarrergit Did you get any solution I am also facing same issue. As first it was running well but now same problem arises
> 
> I am using hugchat version 0.4.10

Had the same problem, but reinstalling the new version (0.4.11) helped
